"""empty message

Revision ID: 724e060411a1
Revises: ec043ed48639
Create Date: 2022-04-07 12:33:24.137945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724e060411a1'
down_revision = 'ec043ed48639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
